"""init_tables

Revision ID: 3fba177e88ce
Revises: 
Create Date: 2026-04-05 18:31:36.084095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fba177e88ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')

    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False, comment='Id'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='Relative file path'),
    sa.Column('sha', sa.String(length=200), nullable=False, comment='File hash'),
    sa.Column('size_bytes', sa.Float(), nullable=False, comment='File size in bytes'),
    sa.Column('type', sa.Enum('code', 'doc', 'unknown', name='filetype'), nullable=False, comment='File type'),
    sa.Column('content', sa.Text(), nullable=False, comment='File content'),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_files_content_trgm', 'files', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.create_index('ix_files_search_vector', 'files', ['search_vector'], unique=False, postgresql_using='gin')

    op.execute("""
        CREATE OR REPLACE FUNCTION update_files_search_vector()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.search_vector := 
                setweight(to_tsvector('simple', COALESCE(NEW.content, '')), 'A') ||
                setweight(to_tsvector('simple', COALESCE(NEW.path, '')), 'B');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """)

    op.execute("""
        CREATE TRIGGER files_search_vector_trigger
        BEFORE INSERT OR UPDATE OF content, path
        ON files
        FOR EACH ROW
        EXECUTE FUNCTION update_files_search_vector();
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_files_search_vector', table_name='files', postgresql_using='gin')
    op.drop_index('ix_files_content_trgm', table_name='files', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.drop_table('files')

    op.execute('DROP TYPE IF EXISTS filetype')

    op.execute('DROP FUNCTION IF EXISTS update_files_search_vector')
    op.execute('DROP TRIGGER IF EXISTS files_search_vector_trigger on files')
    op.execute('DROP EXTENSION IF EXISTS pg_trgm')
    # ### end Alembic commands ###
