"""init_tables

Revision ID: 942d76aab7c3
Revises: 
Create Date: 2026-03-12 23:39:29.482394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942d76aab7c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False, comment='Id'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='Relative file path'),
    sa.Column('sha', sa.String(length=200), nullable=False, comment='File hash'),
    sa.Column('size_bytes', sa.Float(), nullable=False, comment='File size in bytes'),
    sa.Column('type', sa.Enum('code', 'doc', 'unknown', name='filetype'), nullable=False, comment='File type'),
    sa.Column('content', sa.Text(), nullable=False, comment='File content'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False, comment='Id'),
    sa.Column('content', sa.Text(), nullable=False, comment='Insight text'),
    sa.Column('insight_type', sa.Enum('code_explanation', 'potential_problem', 'architecture', 'security', 'performance', name='insighttype'), nullable=False, comment='Insight type'),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', 'suggestion', name='insightseverity'), nullable=False, comment='Insight severity'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='Confidence score [0-1]'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insights')
    op.drop_table('files')
    # ### end Alembic commands ###
