"""init_tables

Revision ID: be6bb45a8e88
Revises: 
Create Date: 2026-02-27 11:48:34.727365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be6bb45a8e88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False, comment='Id'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='Relative file path'),
    sa.Column('sha', sa.String(length=200), nullable=False, comment='File hash'),
    sa.Column('size_bytes', sa.Float(), nullable=False, comment='File size in bytes'),
    sa.Column('type', sa.Enum('CODE', 'DOC', 'UNKNOWN', name='filetype'), nullable=False, comment='File type'),
    sa.Column('content', sa.Text(), nullable=False, comment='File content'),
    sa.Column('search_vector', postgresql.TSVECTOR(), server_default="\n            to_tsvector('Language.RU', <sqlalchemy.orm.properties.MappedColumn object at 0x000002DF7B8C8430>)\n        ", nullable=True, comment='Full-text search vector'),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_files_search_vector', 'files', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_files_search_vector', table_name='files', postgresql_using='gin')
    op.drop_table('files')
    # ### end Alembic commands ###
