"""init_tables

Revision ID: f24da8f10734
Revises: 
Create Date: 2026-03-01 19:00:01.595090

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f24da8f10734'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False, comment='Id'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='Relative file path'),
    sa.Column('sha', sa.String(length=200), nullable=False, comment='File hash'),
    sa.Column('size_bytes', sa.Float(), nullable=False, comment='File size in bytes'),
    sa.Column('type', sa.Enum('CODE', 'DOC', 'UNKNOWN', name='filetype'), nullable=False, comment='File type'),
    sa.Column('content', sa.Text(), nullable=False, comment='File content'),
    sa.Column('search_vector', postgresql.TSVECTOR(), server_default="\n            to_tsvector('Language.RU', <sqlalchemy.orm.properties.MappedColumn object at 0x00000168536216C0>)\n        ", nullable=True, comment='Full-text search vector'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_files_search_vector', 'files', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('file_chunks',
    sa.Column('id', sa.UUID(), nullable=False, comment='Id'),
    sa.Column('file_id', sa.UUID(), nullable=False, comment='File id'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Index of chunk'),
    sa.Column('content', sa.Text(), nullable=False, comment='Content of chunk'),
    sa.Column('embedding', Vector(dim=1024), nullable=False, comment='Embedding of chunk'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_file_chunks_embedding', 'file_chunks', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_table('python_dependency_graph',
    sa.Column('id', sa.UUID(), nullable=False, comment='Id'),
    sa.Column('file_id', sa.UUID(), nullable=False, comment='Child file id'),
    sa.Column('parent_id', sa.UUID(), nullable=False, comment='Parent file id'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('python_dependency_graph')
    op.drop_index('idx_file_chunks_embedding', table_name='file_chunks', postgresql_using='ivfflat')
    op.drop_table('file_chunks')
    op.drop_index('idx_files_search_vector', table_name='files', postgresql_using='gin')
    op.drop_table('files')
    op.execute('DROP EXTENSION IF EXISTS vector')
    # ### end Alembic commands ###
